#!/bin/bash

# Screenshot Collection Helper
# This helps you organize screenshots for training

echo "=================================="
echo "SCREENSHOT COLLECTION HELPER"
echo "=================================="
echo ""
echo "This will help you collect training data"
echo ""

# Create screenshots folder
SCREENSHOT_DIR="$HOME/Desktop/screen-training-screenshots"
mkdir -p "$SCREENSHOT_DIR"

echo "✓ Created folder: $SCREENSHOT_DIR"
echo ""
echo "=================================="
echo "HOW TO TAKE SCREENSHOTS:"
echo "=================================="
echo ""
echo "Mac:"
echo "  Cmd + Shift + 4  → Select area"
echo "  Cmd + Shift + 4 + Spacebar → Capture window"
echo "  Cmd + Shift + 5  → Screenshot tool"
echo ""
echo "=================================="
echo "WHAT TO CAPTURE:"
echo "=================================="
echo ""
echo "Take 200-500 screenshots of:"
echo "  ✓ VS Code with different projects"
echo "  ✓ Browser windows (Chrome, Firefox)"
echo "  ✓ Terminal windows"
echo "  ✓ Multiple windows at once"
echo "  ✓ Different window sizes"
echo "  ✓ Different arrangements"
echo ""
echo "=================================="
echo "TIPS:"
echo "=================================="
echo ""
echo "1. Vary your setup between screenshots"
echo "2. Include partial windows (not just full screen)"
echo "3. Mix light and dark themes"
echo "4. Different times of day"
echo "5. Overlapping windows"
echo ""
echo "=================================="
echo "AFTER TAKING SCREENSHOTS:"
echo "=================================="
echo ""
echo "1. Move them to: $SCREENSHOT_DIR"
echo ""
echo "   Run this command:"
echo "   mv ~/Desktop/Screenshot*.png $SCREENSHOT_DIR/"
echo ""
echo "2. Go to: https://roboflow.com"
echo "3. Upload all screenshots"
echo "4. Label the regions (draw boxes)"
echo "5. Download as 'YOLOv8' format"
echo "6. Extract to: training/dataset/"
echo ""
echo "=================================="
echo ""
echo "Ready to start? (Press Enter)"
read

# Open the folder
open "$SCREENSHOT_DIR"

echo ""
echo "✓ Folder opened!"
echo ""
echo "Start taking screenshots now!"
echo "Save them to: $SCREENSHOT_DIR"
echo ""
echo "Current count:"
ls -1 "$SCREENSHOT_DIR" 2>/dev/null | wc -l | xargs echo "Screenshots:"
echo ""
echo "Target: 200-500 screenshots"
echo ""
echo "Run this script again to check your progress!"
echo ""
